import Link from 'next/link';
import './globals.css';
import LoginBtn from './components/LoginBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { UserType } from '../types/UserType';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  let session = await getServerSession(authOptions);
  // console.log(session);
  return (
    <html lang='en'>
      <body>
        <header>
          <div className='gnb_wrap'>
            <h1>
              <Link
                href='/'
                className='logo'>
                Catcha
              </Link>
            </h1>

            <nav className='gnb'>
              <ul>
                <li>
                  <Link href='/review'>review</Link>
                </li>
                <li>
                  <Link href='/shop'>shop</Link>
                </li>
                <li>
                  <Link href='/ranking'>ranking</Link>
                </li>
              </ul>
            </nav>
            {!session ? (
              <Link
                className='register_btn'
                href='/register'>
                register
              </Link>
            ) : (
              <Link
                className='register_btn'
                href='/mypage'>
                my page
              </Link>
            )}
            <LoginBtn user={session ? (session.user as UserType) : null} />
          </div>
        </header>

        {children}

        <div className='go-top'>
          <button
            type='button'
            className='go-top-btn'>
            <span>TOP</span>
          </button>
        </div>
        <footer>
          <div className='footer-row-wrap'>
            <div>
              <h2>contact me</h2>
              <ul>
                <li>
                  <a
                    target='_blank'
                    href='https://www.google.com/intl/ko/gmail/about/'>
                    Gmail
                  </a>
                  :<span>kimhyosun0535@gmail.com</span>
                </li>
                <li>
                  <a
                    target='_blank'
                    href='https://www.rocketpunch.com/@ae51bdbc'>
                    rocketpunch
                  </a>
                </li>
              </ul>
            </div>
            <address>namoo93 github portfolio.</address>
          </div>
        </footer>
      </body>
    </html>
  );
}
