import Link from 'next/link';
import './globals.css';
import LoginBtn from './LoginBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { UserType } from '../types/UserType';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  let session = await getServerSession(authOptions);
  // console.log(session);
  return (
    <html lang='en'>
      <body>
        <header>
          <div className='gnb_wrap'>
            <h1>
              <Link
                href='/'
                className='logo'>
                Catcha
              </Link>
            </h1>

            <nav className='gnb'>
              <ul>
                <li>
                  <Link href='/list'>review</Link>
                </li>
                <li>
                  <Link href='/list'>shop</Link>
                </li>
                <li>
                  <Link href='/list'>ranking</Link>
                </li>
              </ul>
            </nav>
            {!session ? (
              <Link
                className='register_btn'
                href='/register'>
                register
              </Link>
            ) : (
              <Link
                className='register_btn'
                href='/list'>
                my page
              </Link>
            )}
            <LoginBtn user={session ? (session.user as UserType) : null} />
          </div>
        </header>

        {children}
        <footer></footer>
      </body>
    </html>
  );
}
